name: Scheduled Sync Test

on:
  schedule:
    - cron: '0 */3 * * *'  # every 3 hours
  workflow_dispatch:      # allow manual run

jobs:
  run-sync-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run sync test
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: npm start
